:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\DropTablesScript.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\CreateTablesScript.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateAddCalendarEventSP.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateAddChatMessage.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateAddNoteSP.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateAddReceivedMessage.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateGetCalendarEventsSP.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateGetChatMessages.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\CreateStockTransaction.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\DeleteCalendarEvent.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\GetStockTransactions.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\ReturnStockNote.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\DeleteStockHistory.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\GetStockhistory.sql"
:r "C:\Users\Brian\Desktop\Work\4th Year\Fall\Web Engineering\Web Project\Database Scripts\\Stored Procedures\GetUniqueStocks.sql"
