:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\DropTablesScript.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\CreateTablesScript.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateAddCalendarEventSP.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateAddChatMessage.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateAddNoteSP.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateAddReceivedMessage.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateGetCalendarEventsSP.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateGetChatMessages.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\CreateStockTransaction.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\DeleteCalendarEvent.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\GetStockTransactions.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\ReturnStockNote.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\DeleteStockHistory.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\GetStockhistory.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\GetUniqueStocks.sql"
:r "C:\Users\Pop\Documents\Visual Studio 2012\Projects\344WebApp\Database Scripts\\Stored Procedures\DeleteStockNote.sql"
